[0m17:11:54.980082 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x785322e85d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7853232d4690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x785322e6c390>]}


============================== 17:11:54.985108 | 2297f69f-0077-47ee-b200-f8454e011a3d ==============================
[0m17:11:54.985108 [info ] [MainThread]: Running with dbt=1.8.4
[0m17:11:54.985984 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/guilherme/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:12:00.388389 [debug] [MainThread]: Starter project path: /home/guilherme/.pyenv/versions/3.11.9/lib/python3.11/site-packages/dbt/include/starter_project
[0m17:12:00.421131 [info ] [MainThread]: 
Your new dbt project "sales" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:12:00.428950 [info ] [MainThread]: Setting up your profile.
[0m17:12:00.440249 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m17:12:00.454470 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 5.541506, "process_user_time": 2.048304, "process_kernel_time": 0.168695, "process_mem_max_rss": "90248", "process_out_blocks": "72", "command_success": false, "process_in_blocks": "0"}
[0m17:12:00.462568 [debug] [MainThread]: Command `dbt init` failed at 17:12:00.461090 after 5.55 seconds
[0m17:12:00.467743 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x785322e7b3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x785322e280d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x785322ef9050>]}
[0m17:12:00.473516 [debug] [MainThread]: Flushing usage events
